FROM mcr.microsoft.com/devcontainers/python:1-3.12

RUN \
    python -m pip install --upgrade pip && \
    python -m pip install poetry && \
    poetry self add poetry-plugin-export


ENV SHELL /bin/bash